services:

  backend:
    build: ./backend
    container_name: fwds-backend
    ports:
      - "8081:8081"
    depends_on:
      - ml-service
    environment:
      - ML_URL=http://ml-service:8000
    restart: unless-stopped

  ml-service:
    build: ./ml-service
    container_name: fwds-ml
    ports:
      - "8000:8000"
    restart: unless-stopped

  log-service:
    build: ./log-service
    container_name: fwds-logs
    ports:
      - "3000:3000"
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  mail-service:
    build: ./mail-service
    container_name: fwds-mail
    ports:
      - "3001:3001"
    environment:
      - MAIL_SERVICE_PORT=3001
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ALERT_EMAIL=shreeyash.santosh2023@vitstudent.ac.in
    restart: unless-stopped
